version: 2.1

jobs:
 build:
  docker: 
   - image: circleci/python:latest
  steps:
      - checkout
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          command: |
            . venv/bin/activate
            python manage.py test
      
workflows:
  main:
    jobs:
      - build
