version: 2.1

jobs:
 build-test:
  docker: 
   - image: circleci/python:latest
  steps:
      - checkout
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -U pytest
            pip install -r requirements.txt
      - run:
          command: |
            . venv/bin/activate
            pytest
 deploy:
  docker: 
   - image: circleci/python:latest

  steps:
      - checkout
      - run:
          name: Pret a deployer la nouvelle version
          command: |
            echo "on peut deployer car test + build OK"


workflows:
  main:
    jobs:
      - build-test
      - deploy:
          requires:
            - build-test

